# UIT DSC 2026 – LegalQA Generation-Only Smoke Test

Notebook ngắn để kiểm tra **Vi-Qwen2-1.5B-RAG có rút gọn/cắt câu trả lời hay không** mà không xây lại BM25, Dense FAISS hoặc Reranker.

Quy trình:

1. Tự tìm `train.json`, public test và `selected-contexts` theo cùng cơ chế của notebook chính.
2. Ưu tiên `submission_v0.json` làm `CONTEXT` nếu tìm thấy; nếu không có thì dùng các đáp án train dài.
3. So sánh prompt chống tóm tắt ở `max_new_tokens=512` và `1024`.
4. Báo `length_ratio`, mức bảo toàn token, boilerplate, từ chối và dấu hiệu chạm giới hạn token.

> Trên Kaggle, hãy **Add Data** giống notebook chính (dataset LegalQA và output model snapshot nếu có). Nếu không có snapshot, bật Internet để tải model từ Hugging Face. Notebook này không đánh giá retrieval; nó chỉ trả lời câu hỏi “generation có đang rút gọn quá mức không?”.

In [1]:
from __future__ import annotations

import importlib.util
import json
import os
import re
import subprocess
import sys
import time
from collections import Counter
from pathlib import Path

os.environ.setdefault("TOKENIZERS_PARALLELISM", "false")
os.environ.setdefault("PYTORCH_ALLOC_CONF", "expandable_segments:True")

# ===== CẤU HÌNH NHANH =====
REPO_URL = "https://github.com/lighth-gh/uit-dsc-2026-task2-legalqa.git"
GENERATOR_MODEL_ID = "AITeamVN/Vi-Qwen2-1.5B-RAG"
TEST_LIMIT = 10                 # 10 ID x 2 cấu hình; tăng lên 20 nếu muốn
RUN_1024_TEST = True            # False nếu chỉ muốn test 512 nhanh hơn
USE_ACTUAL_QUESTIONS = True     # False: dùng câu lệnh kiểm tra chung
MAX_INPUT_TOKENS_512 = 7168
MAX_INPUT_TOKENS_1024 = 6144
REPETITION_PENALTY = 1.05
SEED = 2026

# Ghi đè đường dẫn nếu auto-discovery chọn sai; để None để tự tìm.
DATASET_DIR = None
TRAIN_PATH = None
PUBLIC_PATH = None
CONTEXTS_PATH = None
SOURCE_SUBMISSION_PATH = None       # Tùy chọn: dùng answer của submission làm CONTEXT
COMPARISON_SUBMISSION_PATH = None   # Tùy chọn: so sánh độ rút ngắn với submission khác
MODEL_PATH = None

# Các ID đã thấy bị rút mạnh/từ chối trong v1.
PRIORITY_IDS = ["34235", "62147", "86293", "80189", "135669"]

if Path("/kaggle/working").is_dir():
    PLATFORM = "Kaggle"
    REPO_DIR = Path("/kaggle/working/uit-dsc-2026-task2-legalqa")
    INPUT_ROOT = Path("/kaggle/input")
    WORK_DIR = Path("/kaggle/working/legalqa-run")
    EXPORT_DIR = Path("/kaggle/working")
elif Path("/content").is_dir():
    PLATFORM = "Colab"
    REPO_DIR = Path("/content/uit-dsc-2026-task2-legalqa")
    INPUT_ROOT = Path("/content")
    WORK_DIR = Path("/content/legalqa-run")
    EXPORT_DIR = WORK_DIR
else:
    PLATFORM = "Local"
    REPO_DIR = Path(".").resolve()
    if not (REPO_DIR / "legalqa_baseline").is_dir():
        candidate = REPO_DIR / "UIT_DSC_2026_LegalQA_baseline_v0.1"
        if candidate.is_dir():
            REPO_DIR = candidate
    INPUT_ROOT = REPO_DIR
    WORK_DIR = REPO_DIR / "artifacts"
    EXPORT_DIR = WORK_DIR

HF_CACHE_DIR = WORK_DIR / "hf-cache"
WORK_DIR.mkdir(parents=True, exist_ok=True)
os.environ["HF_HOME"] = str(HF_CACHE_DIR)
os.environ["HF_HUB_CACHE"] = str(HF_CACHE_DIR / "hub")

print(f"Platform: {PLATFORM}")
print(f"Input root: {INPUT_ROOT}")
print(f"Repo: {REPO_DIR}")
print(f"Work dir: {WORK_DIR}")
print(f"Output: {EXPORT_DIR}")

Platform: Kaggle
Input root: /kaggle/input
Repo: /kaggle/working/uit-dsc-2026-task2-legalqa
Work dir: /kaggle/working/legalqa-run
Output: /kaggle/working

## 1. Cài thư viện tối thiểu

Chỉ cài generator dependencies; không cài FAISS, embedding hoặc reranker.

In [2]:
required = {
    "transformers": "transformers>=4.40.0",
    "accelerate": "accelerate",
    "sentencepiece": "sentencepiece",
    "pandas": "pandas",
}
missing = [package for module, package in required.items() if importlib.util.find_spec(module) is None]
if missing:
    print("Installing:", missing)
    subprocess.check_call([sys.executable, "-m", "pip", "install", "-q", *missing])
else:
    print("Dependencies already available.")

if not (REPO_DIR / "legalqa_baseline").is_dir():
    if REPO_DIR.exists() and any(REPO_DIR.iterdir()):
        raise RuntimeError(f"REPO_DIR tồn tại nhưng không phải project LegalQA: {REPO_DIR}")
    subprocess.check_call(["git", "clone", "--depth", "1", REPO_URL, str(REPO_DIR)])
if str(REPO_DIR) not in sys.path:
    sys.path.insert(0, str(REPO_DIR))

import pandas as pd
import torch
from IPython.display import FileLink, Markdown, display
from transformers import AutoModelForCausalLM, AutoTokenizer, set_seed
from legalqa_baseline.generator import ViQwenRAGGenerator

print("Torch:", torch.__version__)
print("CUDA:", torch.cuda.is_available())
if torch.cuda.is_available():
    for gpu_id in range(torch.cuda.device_count()):
        print(f"  GPU {gpu_id}: {torch.cuda.get_device_name(gpu_id)}")

Dependencies already available.

Cloning into '/kaggle/working/uit-dsc-2026-task2-legalqa'...

Torch: 2.10.0+cu128
CUDA: True
  GPU 0: Tesla T4
  GPU 1: Tesla T4

## 2. Tự tìm dataset, submission tùy chọn và model snapshot

In [3]:
MODEL_MARKER = ".legalqa_model.json"


def search_roots():
    candidates = [
        Path(DATASET_DIR) if DATASET_DIR is not None else None,
        INPUT_ROOT,
        WORK_DIR,
        REPO_DIR,
        REPO_DIR.parent,
        Path("./data"),
        Path(".").resolve(),
    ]
    seen = set()
    for root in candidates:
        if root is None:
            continue
        root = Path(root)
        if not root.exists():
            continue
        key = str(root.resolve())
        if key not in seen:
            seen.add(key)
            yield root


def resolve_file(label, override, accepted_names, required=True):
    if override is not None:
        path = Path(override)
        if not path.is_file():
            raise FileNotFoundError(f"{label} không tồn tại: {path}")
        return path

    accepted = {name.casefold() for name in accepted_names}
    for root in search_roots():
        matches = sorted(
            (path for path in root.rglob("*") if path.is_file() and path.name.casefold() in accepted),
            key=lambda path: (len(path.parts), str(path)),
        )
        if matches:
            return matches[0]
    if required:
        raise FileNotFoundError(f"Không tìm thấy {label}: {sorted(accepted_names)}")
    return None


def resolve_contexts(override):
    if override is not None:
        path = Path(override)
        if not path.exists():
            raise FileNotFoundError(f"selected-contexts không tồn tại: {path}")
        return path

    for root in search_roots():
        candidates = sorted(
            root.rglob("*selected-contexts*"),
            key=lambda path: (len(path.parts), str(path)),
        )
        for path in candidates:
            if not path.is_dir():
                continue
            nested = path / "selected-contexts"
            if nested.is_dir() and any(nested.glob("context_*.json")):
                return nested
            if any(path.glob("context_*.json")) or any(path.rglob("context_*.json")):
                return path
        for path in candidates:
            if path.is_file() and path.suffix.casefold() == ".zip":
                return path
    return None


def model_snapshot_is_complete(model_dir):
    return (
        (model_dir / "config.json").is_file()
        and (
            any(model_dir.glob("*.safetensors"))
            or any(model_dir.glob("pytorch_model*.bin"))
        )
    )


def discover_generator_snapshot():
    if MODEL_PATH is not None:
        model_path = Path(MODEL_PATH)
        return str(model_path) if model_path.exists() else str(MODEL_PATH)
    for root in search_roots():
        for marker in root.rglob(MODEL_MARKER):
            try:
                payload = json.loads(marker.read_text(encoding="utf-8"))
            except (OSError, ValueError):
                continue
            if payload.get("repo_id") == GENERATOR_MODEL_ID and model_snapshot_is_complete(marker.parent):
                print(f"Tái sử dụng generator snapshot: {marker.parent}")
                return str(marker.parent)
    print("Không thấy snapshot; sẽ tải generator từ Hugging Face.")
    return GENERATOR_MODEL_ID


TRAIN_PATH = resolve_file("train set", TRAIN_PATH, {"train.json"})
PUBLIC_PATH = resolve_file(
    "public test",
    PUBLIC_PATH,
    {"public-official.json", "public-official(1).json", "public_official.json", "public_test.json"},
)
CONTEXTS_PATH = resolve_contexts(CONTEXTS_PATH)
SOURCE_SUBMISSION_PATH = resolve_file(
    "source submission",
    SOURCE_SUBMISSION_PATH,
    {"submission_v0.json"},
    required=False,
)
COMPARISON_SUBMISSION_PATH = resolve_file(
    "comparison submission",
    COMPARISON_SUBMISSION_PATH,
    {"submission_v1.json", "submission_v1(1).json", "submission_rag.json"},
    required=False,
)
GENERATOR_MODEL = discover_generator_snapshot()

print("train:", TRAIN_PATH)
print("public:", PUBLIC_PATH)
print("selected-contexts:", CONTEXTS_PATH or "không có — generation-only không cần retrieval")
print("source submission:", SOURCE_SUBMISSION_PATH or "không có — dùng đáp án train")
print("comparison submission:", COMPARISON_SUBMISSION_PATH or "không có")
print("generator:", GENERATOR_MODEL)

Không thấy snapshot; sẽ tải generator từ Hugging Face.
train: /kaggle/input/datasets/lighth/uit-dsc-2026-task2-legalqa-train/train.json
public: /kaggle/input/datasets/lighth/uit-dsc-2026-task2-legalqa-train/public-official.json
selected-contexts: /kaggle/input/datasets/lighth/uit-dsc-2026-task2-legalqa-train/selected-contexts/selected-contexts
source submission: không có — dùng đáp án train
comparison submission: không có
generator: AITeamVN/Vi-Qwen2-1.5B-RAG

## 3. Chọn các đáp án dài để kiểm tra

Notebook ưu tiên `submission_v0.json` nếu tự tìm thấy hoặc được chỉ định qua `SOURCE_SUBMISSION_PATH`; câu hỏi tương ứng lấy từ public test. Nếu không có submission nguồn, notebook dùng câu hỏi/đáp án từ `train.json`. Khi có comparison submission, các ID bị rút ngắn mạnh được ưu tiên.

In [4]:
def load_json(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


train_data = load_json(TRAIN_PATH)
public_data = load_json(PUBLIC_PATH)
source_submission = load_json(SOURCE_SUBMISSION_PATH) if SOURCE_SUBMISSION_PATH else {}
comparison_data = load_json(COMPARISON_SUBMISSION_PATH) if COMPARISON_SUBMISSION_PATH else {}

assert isinstance(train_data, dict) and train_data, "train.json phải là JSON object không rỗng"
assert isinstance(public_data, dict) and public_data, "public test phải là JSON object không rỗng"

if source_submission:
    assert all(
        isinstance(value, dict) and isinstance(value.get("answer"), str)
        for value in source_submission.values()
    ), "source submission phải có dạng {id: {'answer': str}}"
    source_data = source_submission
    question_data = public_data
    source_label = str(SOURCE_SUBMISSION_PATH)
else:
    source_data = {
        str(qid): {"answer": str(item["answer"])}
        for qid, item in train_data.items()
        if isinstance(item, dict) and isinstance(item.get("answer"), str)
    }
    question_data = train_data
    source_label = str(TRAIN_PATH)

questions = {
    str(qid): str(item.get("question") or "")
    for qid, item in question_data.items()
    if isinstance(item, dict)
}
assert source_data, "Không có answer nguồn để chạy smoke test"

common_ids = set(source_data) & set(comparison_data) if comparison_data else set(source_data)
if comparison_data:
    ranked_ids = sorted(
        common_ids,
        key=lambda qid: len(source_data[qid]["answer"]) - len(comparison_data[qid].get("answer", "")),
        reverse=True,
    )
else:
    ranked_ids = sorted(common_ids, key=lambda qid: len(source_data[qid]["answer"]), reverse=True)

selected_ids = []
for qid in PRIORITY_IDS + ranked_ids:
    if qid in common_ids and qid not in selected_ids:
        selected_ids.append(qid)
    if len(selected_ids) >= TEST_LIMIT:
        break

selection_rows = []
for qid in selected_ids:
    source = source_data[qid]["answer"]
    comparison = comparison_data.get(qid, {}).get("answer", "")
    selection_rows.append({
        "id": qid,
        "question": questions.get(qid, ""),
        "source_chars": len(source),
        "comparison_chars": len(comparison) if comparison else None,
        "shrink_chars": len(source) - len(comparison) if comparison else None,
    })

selection_df = pd.DataFrame(selection_rows)
display(selection_df)
print(f"Nguồn context: {source_label}")
print(f"Đã chọn {len(selected_ids)} ID: {selected_ids}")

,id,question,source_chars,comparison_chars,shrink_chars
0,37801,Thủ tục phê duyệt và cấp bảo lãnh Chính phủ đố...,10755,None,None
1,118227,Thời điểm lập hóa đơn thuế GTGT năm 2023 được ...,9719,None,None
2,79987,Vay ưu đãi để thuê mua nhà ở xã hội theo thủ t...,9128,None,None
3,113337,"Quản lý, giám sát hoạt động của tàu cá giữa bi...",8089,None,None
4,131625,Bản đồ địa chính theo Luật đất đai thể hiện nh...,8082,None,None
5,120573,Các cơ sở kinh doanh dịch vụ karaoke trong mỗi...,7844,None,None
6,113663,Đơn đăng ký bảo hộ logo công ty phải đáp ứng n...,7674,None,None
7,12581,"Trình tự, thủ tục chuyển nhượng hợp đồng mua b...",7568,None,None
8,61739,Hướng dẫn về nội dung và phương pháp lập các c...,7498,None,None
9,164923,Mặt hàng cẩu trục có chịu thuế giá trị gia tăn...,6963,None,None

Nguồn context: /kaggle/input/datasets/lighth/uit-dsc-2026-task2-legalqa-train/train.json
Đã chọn 10 ID: ['37801', '118227', '79987', '113337', '131625', '120573', '113663', '12581', '61739', '164923']

## 4. Load riêng Vi-Qwen2-1.5B-RAG

Cell này là bước nặng duy nhất. Không load embedding model hoặc reranker.

In [5]:
set_seed(SEED)

tokenizer = AutoTokenizer.from_pretrained(
    GENERATOR_MODEL,
    trust_remote_code=False,
)

load_kwargs = {
    "trust_remote_code": False,
    "low_cpu_mem_usage": True,
}
if torch.cuda.is_available():
    load_kwargs.update({
        "device_map": "auto",
        "torch_dtype": torch.float16,
    })
else:
    load_kwargs["torch_dtype"] = torch.float32

model = AutoModelForCausalLM.from_pretrained(
    GENERATOR_MODEL,
    **load_kwargs,
)
model.eval()

MODEL_DEVICE = next(model.parameters()).device
prompt_helper = ViQwenRAGGenerator(
    model_name_or_path=GENERATOR_MODEL,
    max_new_tokens=512,
    max_input_tokens=MAX_INPUT_TOKENS_512,
    repetition_penalty=REPETITION_PENALTY,
    seed=SEED,
)
prompt_helper._tokenizer = tokenizer
prompt_helper._model = model

print("Model device:", MODEL_DEVICE)
print("Model loaded:", GENERATOR_MODEL)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/709 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

added_tokens.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/613 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/3.09G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/338 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

Model device: cuda:0
Model loaded: AITeamVN/Vi-Qwen2-1.5B-RAG

## 5. Prompt chống tóm tắt và hàm audit

In [6]:
GENERIC_QUESTION = (
    "Hãy trả lại đầy đủ nội dung pháp lý cần thiết trong CONTEXT. "
    "Không tóm tắt, không lược bỏ danh sách, điều khoản hoặc biểu mẫu."
)


@torch.inference_mode()
def generate_one(question, context, max_input_tokens, max_new_tokens):
    model_context = int(
        getattr(model.config, "max_position_embeddings", max_input_tokens)
    )
    if max_new_tokens >= model_context:
        raise ValueError(
            f"max_new_tokens={max_new_tokens} phải nhỏ hơn context window={model_context}"
        )
    prompt_limit = min(max_input_tokens, model_context - max_new_tokens)
    inputs = prompt_helper._prepare_inputs(
        context=context,
        question=question or GENERIC_QUESTION,
        prompt_limit=prompt_limit,
    )
    inputs = {key: value.to(MODEL_DEVICE) for key, value in inputs.items()}
    input_length = inputs["input_ids"].shape[1]

    generate_kwargs = {
        "max_new_tokens": max_new_tokens,
        "do_sample": False,
        "repetition_penalty": REPETITION_PENALTY,
    }
    eos_token_id, pad_token_id = prompt_helper._generation_token_ids()
    if eos_token_id is not None:
        generate_kwargs["eos_token_id"] = eos_token_id
    if pad_token_id is not None:
        generate_kwargs["pad_token_id"] = pad_token_id

    started = time.time()
    outputs = model.generate(
        **inputs,
        **generate_kwargs,
    )
    elapsed = time.time() - started

    generated_ids = outputs[0, input_length:]
    answer = tokenizer.decode(generated_ids, skip_special_tokens=True).strip()
    return {
        "answer": answer,
        "input_tokens": int(input_length),
        "generated_tokens": int(generated_ids.shape[0]),
        "hit_token_limit": bool(generated_ids.shape[0] >= max_new_tokens - 4),
        "seconds": round(elapsed, 2),
    }


def word_tokens(text):
    return re.findall(r"\w+", text.lower(), flags=re.UNICODE)


def source_coverage(source, prediction):
    src = Counter(word_tokens(source))
    pred = Counter(word_tokens(prediction))
    if not src:
        return 0.0
    return sum((src & pred).values()) / sum(src.values())


def audit(source, generated):
    answer = generated["answer"].strip()
    lower = answer.lower()
    source_words = len(word_tokens(source))
    answer_words = len(word_tokens(answer))
    possibly_cut = bool(
        len(answer) > 100
        and not answer.endswith((".", "!", "?", ")", "]", "}", '"', "”"))
    )
    result = {
        **generated,
        "source_words": source_words,
        "answer_words": answer_words,
        "length_ratio": round(answer_words / max(1, source_words), 3),
        "source_coverage": round(source_coverage(source, answer), 3),
        "has_boilerplate": bool("dựa trên ngữ cảnh" in lower or "theo ngữ cảnh" in lower),
        "says_no_information": bool("không đủ thông tin" in lower or "không có thông tin" in lower),
        "possibly_cut": possibly_cut,
    }
    result["passes_smoke_test"] = bool(
        not result["hit_token_limit"]
        and not result["has_boilerplate"]
        and not result["says_no_information"]
        and not result["possibly_cut"]
        and result["length_ratio"] >= 0.70
        and result["source_coverage"] >= 0.65
    )
    return result

## 6. Chạy smoke test 512 và 1024 token

Mỗi ID dùng đúng cùng một source context. Vì vậy khác biệt ở kết quả đến từ prompt/generation, không phải retrieval.

In [7]:
configs = [
    ("strict_512", MAX_INPUT_TOKENS_512, 512),
]
if RUN_1024_TEST:
    configs.append(("strict_1024", MAX_INPUT_TOKENS_1024, 1024))

all_results = []
for item_index, qid in enumerate(selected_ids, start=1):
    context = source_data[qid]["answer"]
    question = (
        questions.get(qid) or GENERIC_QUESTION
        if USE_ACTUAL_QUESTIONS
        else GENERIC_QUESTION
    )
    print(f"\n[{item_index}/{len(selected_ids)}] ID={qid} | context={len(word_tokens(context))} words")

    for config_name, max_input_tokens, max_new_tokens in configs:
        generated = generate_one(
            question=question,
            context=context,
            max_input_tokens=max_input_tokens,
            max_new_tokens=max_new_tokens,
        )
        checked = audit(context, generated)
        record = {
            "id": qid,
            "config": config_name,
            "question": question,
            **checked,
        }
        all_results.append(record)
        print(
            f"  {config_name}: words={checked['answer_words']} "
            f"ratio={checked['length_ratio']:.3f} coverage={checked['source_coverage']:.3f} "
            f"tokens={checked['generated_tokens']} hit_limit={checked['hit_token_limit']} "
            f"pass={checked['passes_smoke_test']} ({checked['seconds']}s)"
        )

RESULT_JSON = EXPORT_DIR / "legalqa_generation_smoke_test_results.json"
RESULT_CSV = EXPORT_DIR / "legalqa_generation_smoke_test_summary.csv"

RESULT_JSON.write_text(
    json.dumps(all_results, ensure_ascii=False, indent=2),
    encoding="utf-8",
)

summary_columns = [
    "id", "config", "source_words", "answer_words", "length_ratio",
    "source_coverage", "generated_tokens", "hit_token_limit",
    "has_boilerplate", "says_no_information", "possibly_cut",
    "passes_smoke_test", "seconds",
]
result_df = pd.DataFrame(all_results)
result_df[summary_columns].to_csv(RESULT_CSV, index=False, encoding="utf-8-sig")

print("\nSaved:", RESULT_JSON)
print("Saved:", RESULT_CSV)

The following generation flags are not valid and may be ignored: ['temperature', 'top_p', 'top_k']. Set `TRANSFORMERS_VERBOSITY=info` for more details.

[1/10] ID=37801 | context=2401 words
  strict_512: words=382 ratio=0.159 coverage=0.156 tokens=512 hit_limit=True pass=False (28.05s)
  strict_1024: words=532 ratio=0.222 coverage=0.214 tokens=692 hit_limit=False pass=False (35.17s)

[2/10] ID=118227 | context=2137 words
  strict_512: words=141 ratio=0.066 coverage=0.058 tokens=177 hit_limit=False pass=False (9.89s)
  strict_1024: words=141 ratio=0.066 coverage=0.058 tokens=177 hit_limit=False pass=False (9.85s)

[3/10] ID=79987 | context=2096 words
  strict_512: words=369 ratio=0.176 coverage=0.173 tokens=512 hit_limit=True pass=False (26.19s)
  strict_1024: words=746 ratio=0.356 coverage=0.352 tokens=1024 hit_limit=True pass=False (50.15s)

[4/10] ID=113337 | context=1826 words
  strict_512: words=380 ratio=0.208 coverage=0.208 tokens=512 hit_limit=True pass=False (25.85s)
  strict_1024: words=801 ratio=0.439 coverage=0.438 tokens=1024 hit_limit=True pass=False (50.12s)

[5/10] ID=131625 | context=1763 words
  strict_512: words=375 ratio=0.213 coverage=0.198 tokens=512 hit_limit=True pass=False (25.36s)
  strict_1024: words=768 ratio=0.436 coverage=0.417 tokens=1024 hit_limit=True pass=False (49.09s)

[6/10] ID=120573 | context=1734 words
  strict_512: words=73 ratio=0.042 coverage=0.039 tokens=104 hit_limit=False pass=False (6.04s)
  strict_1024: words=73 ratio=0.042 coverage=0.039 tokens=104 hit_limit=False pass=False (6.02s)

[7/10] ID=113663 | context=1745 words
  strict_512: words=375 ratio=0.215 coverage=0.210 tokens=512 hit_limit=True pass=False (25.32s)
  strict_1024: words=690 ratio=0.395 coverage=0.382 tokens=925 hit_limit=False pass=False (45.92s)

[8/10] ID=12581 | context=1674 words
  strict_512: words=391 ratio=0.234 coverage=0.234 tokens=512 hit_limit=True pass=False (26.31s)
  strict_1024: words=798 ratio=0.477 coverage=0.475 tokens=1024 hit_limit=True pass=False (50.16s)

[9/10] ID=61739 | context=1625 words
  strict_512: words=330 ratio=0.203 coverage=0.201 tokens=512 hit_limit=True pass=False (26.65s)
  strict_1024: words=726 ratio=0.447 coverage=0.445 tokens=1024 hit_limit=True pass=False (50.0s)

[10/10] ID=164923 | context=1487 words
  strict_512: words=158 ratio=0.106 coverage=0.075 tokens=214 hit_limit=False pass=False (11.01s)
  strict_1024: words=158 ratio=0.106 coverage=0.075 tokens=214 hit_limit=False pass=False (11.09s)

Saved: /kaggle/working/legalqa_generation_smoke_test_results.json
Saved: /kaggle/working/legalqa_generation_smoke_test_summary.csv

## 7. Kết luận nhanh

- `hit_token_limit=True`: ngân sách output chưa đủ; câu có khả năng bị cắt.
- `length_ratio < 0.70` hoặc `source_coverage < 0.65`: model vẫn rút quá mạnh với câu dài.
- Nếu 1024 vẫn thất bại, không nên bắt model sinh lại toàn bộ; submission nên trả raw chunk tốt nhất + chunk liền kề.

In [8]:
summary_columns = [
    "id", "config", "source_words", "answer_words", "length_ratio",
    "source_coverage", "generated_tokens", "hit_token_limit",
    "has_boilerplate", "says_no_information", "possibly_cut",
    "passes_smoke_test", "seconds",
]

display(result_df[summary_columns].sort_values(["config", "passes_smoke_test", "length_ratio"]))

aggregate = result_df.groupby("config").agg(
    samples=("id", "count"),
    pass_rate=("passes_smoke_test", "mean"),
    mean_length_ratio=("length_ratio", "mean"),
    mean_source_coverage=("source_coverage", "mean"),
    hit_limit_rate=("hit_token_limit", "mean"),
    boilerplate_rate=("has_boilerplate", "mean"),
    no_information_rate=("says_no_information", "mean"),
    mean_seconds=("seconds", "mean"),
).reset_index()
display(aggregate)

best_config = aggregate.sort_values(
    ["pass_rate", "mean_source_coverage", "mean_length_ratio"],
    ascending=False,
).iloc[0]

print(f"Cấu hình tốt nhất trong smoke test: {best_config['config']}")
print(f"Pass rate: {best_config['pass_rate']:.1%}")

if best_config["pass_rate"] < 0.80:
    print("KẾT LUẬN: Generation vẫn không ổn định với đáp án dài. Hãy dùng raw context + adjacent chunks làm fallback khi submission.")
else:
    print("KẾT LUẬN: Prompt/token budget đã đủ tốt trên mẫu dài. Tiếp tục test thêm 20–50 câu trước submission.")

display(FileLink(str(RESULT_JSON)))
display(FileLink(str(RESULT_CSV)))

,id,config,source_words,answer_words,length_ratio,source_coverage,generated_tokens,hit_token_limit,has_boilerplate,says_no_information,possibly_cut,passes_smoke_test,seconds
11,120573,strict_1024,1734,73,0.042,0.039,104,False,False,False,False,False,6.02
3,118227,strict_1024,2137,141,0.066,0.058,177,False,True,True,False,False,9.85
19,164923,strict_1024,1487,158,0.106,0.075,214,False,False,True,False,False,11.09
1,37801,strict_1024,2401,532,0.222,0.214,692,False,True,False,False,False,35.17
5,79987,strict_1024,2096,746,0.356,0.352,1024,True,True,False,True,False,50.15
13,113663,strict_1024,1745,690,0.395,0.382,925,False,True,False,False,False,45.92
9,131625,strict_1024,1763,768,0.436,0.417,1024,True,False,False,True,False,49.09
7,113337,strict_1024,1826,801,0.439,0.438,1024,True,False,False,True,False,50.12
17,61739,strict_1024,1625,726,0.447,0.445,1024,True,True,False,True,False,50.00
15,12581,strict_1024,1674,798,0.477,0.475,1024,True,False,False,True,False,50.16
10,120573,strict_512,1734,73,0.042,0.039,104,False,False,False,False,False,6.04
2,118227,strict_512,2137,141,0.066,0.058,177,False,True,True,False,False,9.89
18,164923,strict_512,1487,158,0.106,0.075,214,False,False,True,False,False,11.01
0,37801,strict_512,2401,382,0.159,0.156,512,True,True,False,True,False,28.05
4,79987,strict_512,2096,369,0.176,0.173,512,True,True,False,True,False,26.19
16,61739,strict_512,1625,330,0.203,0.201,512,True,True,False,True,False,26.65
6,113337,strict_512,1826,380,0.208,0.208,512,True,False,False,True,False,25.85
8,131625,strict_512,1763,375,0.213,0.198,512,True,False,False,True,False,25.36
12,113663,strict_512,1745,375,0.215,0.210,512,True,True,False,True,False,25.32
14,12581,strict_512,1674,391,0.234,0.234,512,True,False,False,True,False,26.31

,config,samples,pass_rate,mean_length_ratio,mean_source_coverage,hit_limit_rate,boilerplate_rate,no_information_rate,mean_seconds
0,strict_1024,10,0.0,0.2986,0.2895,0.5,0.5,0.2,35.757
1,strict_512,10,0.0,0.1622,0.1552,0.7,0.5,0.2,21.067

Cấu hình tốt nhất trong smoke test: strict_1024
Pass rate: 0.0%
KẾT LUẬN: Generation vẫn không ổn định với đáp án dài. Hãy dùng raw context + adjacent chunks làm fallback khi submission.

/kaggle/working/legalqa_generation_smoke_test_results.json

/kaggle/working/legalqa_generation_smoke_test_summary.csv

## 8. Xem chi tiết một vài câu

In [9]:
for qid in selected_ids[:3]:
    display(Markdown(f"### ID {qid}"))
    question = (
        questions.get(qid) or GENERIC_QUESTION
        if USE_ACTUAL_QUESTIONS
        else GENERIC_QUESTION
    )
    print("QUESTION:", question)
    print("\nSOURCE CONTEXT:\n", source_data[qid]["answer"])
    for record in all_results:
        if record["id"] == qid:
            print(f"\n--- {record['config']} ---")
            print(record["answer"])

### ID 37801

QUESTION: Thủ tục phê duyệt và cấp bảo lãnh Chính phủ đối với khoản vay nước ngoài của doanh nghiệp

SOURCE CONTEXT:
 (1) Hồ sơ đề nghị phê duyệt cấp bảo lãnh chính phủ đối với khoản vay theo Điều 14 Nghị định 91/2018/NĐ-CP:
Ngoài hồ sơ đã gửi theo quy định tại Điều 11 Nghị định này, người vay đề nghị phê duyệt cấp bảo lãnh chính phủ đối với khoản vay nộp cập nhật cho Bộ Tài chính trực tiếp hoặc thông qua dịch vụ bưu chính các hồ sơ sau:
- Văn bản yêu cầu khoản vay có bảo lãnh chính phủ của người cho vay gửi người vay (bản chính).
- Văn bản đề nghị cấp bảo lãnh chính phủ của doanh nghiệp kèm theo đề xuất ngân hàng phục vụ cho khoản vay được Chính phủ bảo lãnh (bản chính).
- Các văn bản theo quy định tại Điều 11 Nghị định này nếu có bất kỳ điều chỉnh nào so với văn bản đã nộp trước đây.
- Báo cáo nghiên cứu khả thi đã được cấp có thẩm quyền phê duyệt theo quy định của pháp luật về đầu tư và đầu tư công (trường hợp nộp cho Bộ Tài chính báo cáo nghiên cứu tiền khả thi quy định tại điểm a khoản 3 Điều 11) (bản sao có chứng thực).
- Đề án vay (bản chính) được cập nhật ít nhất 06 tháng trước khi nộp hồ sơ đề nghị phê duyệt cấp bảo lãnh chính phủ theo các nội dung nêu tại khoản 4 Điều 11 Nghị định này, đồng thời bổ sung các nội dung sau:
+ Tóm tắt trị giá và các điều kiện của khoản vay đề nghị cấp bảo lãnh theo dự thảo thỏa thuận vay đã được các bên ký tắt và các khoản vay khác (nếu có);
+ Kế hoạch rút vốn tổng thể theo quý của khoản vay;
+ Quyết định của Hội đồng thành viên hoặc Hội đồng quản trị của đối tượng được bảo lãnh về việc bố trí vốn chủ sở hữu tham gia dự án tối thiểu 20% trong tổng mức đầu tư của dự án đã được cấp có thẩm quyền phê duyệt kèm theo kế hoạch bố trí vốn chủ sở hữu hàng năm trong thời kỳ xây dựng theo tiến độ thực hiện dự án.
- Văn bản phê duyệt đề án vay được Chính phủ bảo lãnh của cơ quan đại diện chủ sở hữu đối với đối tượng được bảo lãnh là doanh nghiệp do nhà nước nắm giữ 100% vốn điều lệ (bản chính).
- Dự thảo thỏa thuận vay cuối cùng đã được các bên ký tắt hoặc thỏa thuận vay đã được ký kết, có quy định về số tiền cho vay và yêu cầu bảo lãnh chính phủ (bản sao có chứng thực).
- Báo cáo tài chính 03 năm liền kề gần nhất với thời điểm gửi hồ sơ thẩm định cấp bảo lãnh đã được kiểm toán theo quy định tại khoản 6 Điều 11 Nghị định này (bản sao có chứng thực). Báo cáo tài chính 6 tháng đầu năm trường hợp thời điểm đề nghị cấp bảo lãnh vào nửa cuối năm tài chính.
- Báo cáo chi tiết của Trung tâm thông tin tín dụng Quốc gia Việt Nam về tình hình tín dụng của doanh nghiệp đề nghị bảo lãnh chính phủ (bản in có đóng dấu của ngân hàng cung cấp thông tin).
- Văn bản cam kết theo quy định tại Phụ lục I của Nghị định này (bản chính) kèm theo xác nhận của đại diện có thẩm quyền của công ty mẹ hoặc tổ chức, cá nhân góp vốn từ 65% vốn điều lệ trở lên về việc đảm bảo trả nợ thay trong trường hợp doanh nghiệp đề nghị bảo lãnh chính phủ gặp khó khăn trong việc trả nợ.
- Văn bản cam kết của các tổ chức và cá nhân sở hữu cổ phần hoặc vốn góp từ 5% vốn điều lệ thực góp trở lên về việc cùng nhau nắm giữ tối thiểu 65% vốn điều lệ thực góp trong suốt thời gian bảo lãnh có hiệu lực, kèm theo danh sách các cổ đông, cá nhân nói trên (đối với công ty cổ phần).
- Các văn bản chứng minh dự án đã hoàn thành thủ tục đầu tư theo quy định của pháp luật về đầu tư.
(2) Thẩm định cấp bảo lãnh chính phủ đối với khoản vay theo Điều 15 Nghị định 91/2018/NĐ-CP:
- Trường hợp hồ sơ không đáp ứng các điều kiện theo quy định nêu tại Điều 14 Nghị định này, Bộ Tài chính thông báo cho đối tượng được bảo lãnh để bổ sung trong vòng 05 ngày làm việc sau khi nhận được hồ sơ. Đối tượng được bảo lãnh có trách nhiệm bổ sung hồ sơ gửi Bộ Tài chính trong vòng 10 ngày làm việc.
- Trong vòng 30 ngày kể từ ngày nhận được đầy đủ hồ sơ đề nghị cấp bảo lãnh theo quy định tại Nghị định này từ doanh nghiệp, Bộ Tài chính thẩm định hồ sơ đề nghị cấp bảo lãnh chính phủ và báo cáo Thủ tướng Chính phủ kết quả thẩm định với các nội dung chính sau:
+ Tính hợp lệ của hồ sơ cung cấp;
+ Đánh giá về đối tượng và điều kiện cấp bảo lãnh theo các tiêu chí và điều kiện quy định tại Điều 41 và Điều 43 Luật Quản lý nợ công và Nghị định này;
+ Đánh giá về cơ cấu vốn đầu tư, trong đó xác định rõ nguồn vốn đầu tư (gồm vốn chủ sở hữu, vốn vay) và điều kiện, điều khoản của khoản vay đề nghị cấp bảo lãnh Chính phủ;
+ Đánh giá về tình hình tài chính của doanh nghiệp vay vốn đề nghị được Chính phủ bảo lãnh (hệ số nợ trên vốn chủ sở hữu, hệ số khả năng thanh toán nhanh, hệ số trả nợ dài hạn);
+ Đánh giá phương án tài chính của dự án sử dụng vốn vay và khả năng trả nợ của doanh nghiệp. Việc đánh giá được thực hiện theo Phương pháp phân tích theo “Hệ số trả nợ vay” để xác định Hệ số trả nợ bình quân 05 năm đầu (tối thiểu là 1,20 đối với các dự án có hợp đồng bao tiêu sản phẩm hoặc hệ số 1,25 đối với các dự án khác); phân tích độ nhạy theo “Hệ số trả nợ vay có bảo lãnh”; phân tích độ nhạy theo “Doanh thu”; phân tích độ nhạy theo “Chi phí sản xuất/chi phí vận hành”:
+ Đánh giá về sự phù hợp (loại hình, tính chất, giá trị) của tài sản thế chấp cho khoản vay được Chính phủ bảo lãnh;
+ Đánh giá các rủi ro của dự án có liên quan tới khoản vay được Chính phủ bảo lãnh; rủi ro có liên quan tới khoản vay; rủi ro về tài chính và khả năng trả nợ của người vay, rủi ro về năng lực thực hiện và quản lý dự án của người vay;
+ Tổng số tiền vay và số dự án Chính phủ đã bảo lãnh mà doanh nghiệp đã thực hiện cho tới thời điểm thẩm định cấp bảo lãnh; dư nợ vay được Chính phủ bảo lãnh của doanh nghiệp tại thời điểm thẩm định cấp bảo lãnh;
+ Mức phí bảo lãnh đề nghị áp dụng;
+ Các đề xuất, kiến nghị.
- Trường hợp cần bổ sung thông tin trong quá trình thẩm định, Bộ Tài chính lấy ý kiến của các bộ, cơ quan ngang bộ, cơ quan quản lý ngành về các vấn đề thuộc lĩnh vực quản lý có liên quan đến dự án vay vốn đề nghị cấp bảo lãnh chính phủ; hoặc yêu cầu doanh nghiệp cung cấp các thông tin bổ sung nếu phát sinh trong quá trình thẩm định cấp bảo lãnh cho khoản vay đầu tư dự án (Thiết kế cơ sở được duyệt, Hợp đồng bao tiêu sản phẩm, thuyết minh về công nghệ, thiết bị của dự án đầu tư). Các cơ quan có trách nhiệm trả lời trong vòng 10 ngày làm việc kể từ ngày nhận được văn bản đề nghị của Bộ Tài chính.
(3) Quyết định cấp bảo lãnh chính phủ đối với khoản vay được quy định tại Điều 16 Nghị định 91/2018/NĐ-CP:
- Bộ Tài chính trình Thủ tướng Chính phủ nội dung Thư bảo lãnh cùng với báo cáo kết quả thẩm định cấp bảo lãnh chính phủ.
- Quyết định cấp bảo lãnh chính phủ cho khoản vay do Thủ tướng Chính phủ ban hành theo Quy chế làm việc của Chính phủ và gửi các cơ quan liên quan, gồm các nội dung:
+ Phê duyệt nội dung Thư bảo lãnh và giao Bộ Tài chính phát hành Thư bảo lãnh;
+ Phê duyệt mức phí bảo lãnh chính phủ áp dụng cho khoản vay;
+ Giao Bộ Tư pháp cấp ý kiến pháp lý theo quy định của pháp luật (nếu có);
+ Giao Bộ Ngoại giao phối hợp với Bộ Tài chính chỉ định cơ quan đại diện thích hợp của Việt Nam ở nước ngoài làm Đại diện tiếp nhận hồ sơ tố tụng theo quy định của Thư bảo lãnh (nếu có);
+ Phê duyệt tổ chức khác làm Đại diện tiếp nhận hồ sơ tố tụng theo quy định của Thư bảo lãnh (nếu có);
+ Các nội dung khác.
(4) Cấp bảo lãnh đối với khoản vay được quy định tại Điều 17 Nghị định 91/2018/NĐ-CP:
- Thư bảo lãnh được Bộ Tài chính cấp trên cơ sở Quyết định của Thủ tướng Chính phủ phê duyệt việc cấp bảo lãnh chính phủ cho khoản vay và sau khi Đối tượng được bảo lãnh đã hoàn thành các thủ tục sau:
+ Ký kết với Bộ Tài chính Hợp đồng thế chấp tài sản cho khoản vay được Chính phủ bảo lãnh theo quy định tại Điều 31 Nghị định này;
+ Cung cấp cho Bộ Tài chính bản sao chứng thực Hợp đồng bảo hiểm tài sản thế chấp;
+ Mở Tài khoản Dự án tại ngân hàng phục vụ; thông báo cho Bộ Tài chính bằng văn bản về số tài khoản của Tài khoản Dự án hoặc hợp đồng mở tài khoản dự án;
+ Nộp cho Bộ Tài chính Hợp đồng vay đã được các bên ký chính thức (bản sao có chứng thực);
+ Cung cấp cho Bộ Tài chính toàn bộ tài khoản tiền gửi hiện có tại các tổ chức tín dụng kèm theo xác nhận của tổ chức tín dụng nơi mở tài khoản (bản chính).
- Thư bảo lãnh được cấp trong vòng 07 ngày làm việc kể từ ngày hoàn thành các thủ tục tại khoản 1 Điều này:
+ Đối với khoản vay nước ngoài, Thư bảo lãnh được lập thành 04 bản chính, trong đó: Bộ Tài chính lưu hồ sơ 01 bản, đối tượng được bảo lãnh lưu 01 bản, Bộ Tư pháp lưu 01 bản và 01 bản được chuyển cho người cho vay hoặc đại diện của người cho vay;
+ Đối với khoản vay trong nước, Thư bảo lãnh được lập thành 06 bản chính, trong đó: Bộ Tài chính lưu hồ sơ 02 bản, đối tượng được bảo lãnh lưu 01 bản và 01 bản được chuyển cho người cho vay, 02 bản được gửi cho các cơ quan liên quan.
- Bộ Tài chính quyết định việc cấp thêm số bản chính cho các cơ quan có liên quan không thuộc các đối tượng quy định tại khoản 2 Điều này theo từng trường hợp cụ thể nếu cần thiết.
(5) Thủ tục có liên quan đến hiệu lực của khoản vay nước ngoài được Chính phủ bảo lãnh được quy định tại Điều 18 Nghị định 91/2018/NĐ-CP:
- Đối tượng được bảo lãnh có trách nhiệm thực hiện các thủ tục quy định trong Thỏa thuận vay để Thư bảo lãnh và Thỏa thuận vay có hiệu lực đầy đủ.
- Đối tượng được bảo lãnh có trách nhiệm làm việc với Bộ Tư pháp để được cấp ý kiến pháp lý đối với Thư bảo lãnh cho khoản vay nước ngoài được Chính phủ bảo lãnh.
- Đối tượng được bảo lãnh có trách nhiệm đăng ký khoản vay nước ngoài với Ngân hàng Nhà nước Việt Nam theo quy định của Ngân hàng Nhà nước Việt Nam về quản lý vay, trả nợ nước ngoài của doanh nghiệp.
- Trường hợp thủ tục tố tụng được quy định trong Thỏa thuận vay nước ngoài và Thư bảo lãnh có yêu cầu Đại diện tiếp nhận hồ sơ tố tụng:
+ Đối tượng được bảo lãnh đề xuất với Bộ Tài chính về tổ chức được chọn làm Đại diện tiếp nhận hồ sơ tố tụng cho người vay (đối tượng được bảo lãnh), người bảo lãnh theo yêu cầu của thỏa thuận vay và lấy ý kiến của Bộ Tài chính hoặc ý kiến chấp thuận của Bộ Ngoại giao trong trường hợp là cơ quan đại diện ngoại giao tại nước ngoài trong quá trình đàm phán;
+ Sau khi Thỏa thuận vay được ký kết và cấp bảo lãnh chính phủ, Đối tượng được bảo lãnh gửi mẫu văn bản ủy quyền của Người vay (đối tượng được bảo lãnh) và người bảo lãnh (nếu có) cho tổ chức được lựa chọn làm Đại diện tiếp nhận hồ sơ tố tụng ký xác nhận đồng ý, gửi cho đối tượng được bảo lãnh để gửi tiếp cho Người nhận bảo lãnh và sao gửi cho Bộ Tài chính.
Như vậy, bảo lãnh Chính phủ là cam kết của Chính phủ bằng văn bản bảo lãnh với bên cho vay về việc thực hiện nghĩa vụ trả nợ gốc, lãi trong trường hợp đến hạn trả nợ mà bên vay không thực hiện đầy đủ nghĩa vụ trả nợ. Doanh nghiệp, ngân hàng chính sách nếu đáp ứng các điều kiện theo quy định sẽ thuộc đối tượng áp dụng bảo lãnh Chính phủ.
Doanh nghiệp muốn được bảo lãnh Chính phủ phải thực hiện thủ tục phê duyệt và cấp bảo lãnh Chính phủ đối với doanh nghiệp và thủ tục phê duyệt và cấp bảo lãnh đối với khoản vay của doanh nghiệp theo quy định của pháp luật.

--- strict_512 ---
Dựa trên ngữ cảnh được cung cấp, thủ tục phê duyệt và cấp bảo lãnh Chính phủ đối với khoản vay nước ngoài của doanh nghiệp bao gồm các bước sau:

1. **Hoàn thành thủ tục phê duyệt và cấp bảo lãnh Chính phủ:**
   - Đối tượng được bảo lãnh phải hoàn thành các thủ tục quy định trong Thỏa thuận vay để Thư bảo lãnh và Thỏa thuận vay có hiệu lực đầy đủ.
   - Đối tượng được bảo lãnh có trách nhiệm làm việc với Bộ Tư pháp để được cấp ý kiến pháp lý đối với Thư bảo lãnh cho khoản vay nước ngoài được Chính phủ bảo lãnh.
   - Đối tượng được bảo lãnh có trách nhiệm đăng ký khoản vay nước ngoài với Ngân hàng Nhà nước Việt Nam theo quy định của Ngân hàng Nhà nước Việt Nam về quản lý vay, trả nợ nước ngoài của doanh nghiệp.

2. **Lập và cấp Thư bảo lãnh:**
   - Thư bảo lãnh được Bộ Tài chính lập trên cơ sở Quyết định của Thủ tướng Chính phủ phê duyệt việc cấp bảo lãnh chính phủ cho khoản vay.
   - Thư bảo lãnh được cấp trong vòng 07 ngày làm việc kể từ ngày hoàn thành các thủ tục tại khoản 1 Điều này:
     - Đối với khoản vay nước ngoài, Thư bảo lãnh được lập thành 04 bản chính, trong đó:
       - Bộ Tài chính lưu hồ sơ 01 bản.
       - Đối tượng được bảo lãnh lưu 01 bản.
       - Bộ Tư pháp lưu 01 bản.
       - 01 bản được chuyển cho người cho vay hoặc đại diện của người cho vay.
     - Đối với khoản vay trong nước, Thư bảo lãnh được lập thành 06 bản chính, trong đó:
       - Bộ Tài chính lưu hồ sơ 02 bản.
       - Đối tượng được bảo lãnh lưu 01 bản.
       - 01 bản được chuyển cho người cho vay.
       - 02 bản được gửi cho các cơ quan liên quan.

3. **Cấp thêm số bản chính:**
   - Bộ Tài chính quyết định việc cấp thêm số bản chính cho các cơ quan có liên quan không thuộc các đối tượng quy định tại khoản 2 Điều này theo từng trường hợp cụ thể nếu cần thiết.

4. **Đăng ký và thông báo:**
   - Đối tượng được bảo lãnh có trách nhiệm thực hiện các thủ tục quy

--- strict_1024 ---
Dựa trên ngữ cảnh được cung cấp, thủ tục phê duyệt và cấp bảo lãnh Chính phủ đối với khoản vay nước ngoài của doanh nghiệp bao gồm các bước sau:

1. **Hoàn thành thủ tục phê duyệt và cấp bảo lãnh Chính phủ:**
   - Đối tượng được bảo lãnh phải hoàn thành các thủ tục quy định trong Thỏa thuận vay để Thư bảo lãnh và Thỏa thuận vay có hiệu lực đầy đủ.
   - Đối tượng được bảo lãnh có trách nhiệm làm việc với Bộ Tư pháp để được cấp ý kiến pháp lý đối với Thư bảo lãnh cho khoản vay nước ngoài được Chính phủ bảo lãnh.
   - Đối tượng được bảo lãnh có trách nhiệm đăng ký khoản vay nước ngoài với Ngân hàng Nhà nước Việt Nam theo quy định của Ngân hàng Nhà nước Việt Nam về quản lý vay, trả nợ nước ngoài của doanh nghiệp.

2. **Lập và cấp Thư bảo lãnh:**
   - Thư bảo lãnh được Bộ Tài chính lập trên cơ sở Quyết định của Thủ tướng Chính phủ phê duyệt việc cấp bảo lãnh chính phủ cho khoản vay.
   - Thư bảo lãnh được cấp trong vòng 07 ngày làm việc kể từ ngày hoàn thành các thủ tục tại khoản 1 Điều này:
     - Đối với khoản vay nước ngoài, Thư bảo lãnh được lập thành 04 bản chính, trong đó:
       - Bộ Tài chính lưu hồ sơ 01 bản.
       - Đối tượng được bảo lãnh lưu 01 bản.
       - Bộ Tư pháp lưu 01 bản.
       - 01 bản được chuyển cho người cho vay hoặc đại diện của người cho vay.
     - Đối với khoản vay trong nước, Thư bảo lãnh được lập thành 06 bản chính, trong đó:
       - Bộ Tài chính lưu hồ sơ 02 bản.
       - Đối tượng được bảo lãnh lưu 01 bản.
       - 01 bản được chuyển cho người cho vay.
       - 02 bản được gửi cho các cơ quan liên quan.

3. **Cấp thêm số bản chính:**
   - Bộ Tài chính quyết định việc cấp thêm số bản chính cho các cơ quan có liên quan không thuộc các đối tượng quy định tại khoản 2 Điều này theo từng trường hợp cụ thể nếu cần thiết.

4. **Đăng ký và thông báo:**
   - Đối tượng được bảo lãnh có trách nhiệm thực hiện các thủ tục quy định trong Thỏa thuận vay để Thư bảo lãnh và Thỏa thuận vay có hiệu lực đầy đủ.
   - Đối tượng được bảo lãnh có trách nhiệm làm việc với Bộ Tư pháp để được cấp ý kiến pháp lý đối với Thư bảo lãnh cho khoản vay nước ngoài được Chính phủ bảo lãnh.
   - Đối tượng được bảo lãnh có trách nhiệm đăng ký khoản vay nước ngoài với Ngân hàng Nhà nước Việt Nam theo quy định của Ngân hàng Nhà nước Việt Nam về quản lý vay, trả nợ nước ngoài của doanh nghiệp.

Như vậy, thủ tục phê duyệt và cấp bảo lãnh Chính phủ đối với khoản vay nước ngoài của doanh nghiệp bao gồm các bước từ hoàn thiện thủ tục phê duyệt và cấp bảo lãnh, lập và cấp Thư bảo lãnh, đến đăng ký và thông báo với các cơ quan liên quan.

### ID 118227

QUESTION: Thời điểm lập hóa đơn thuế GTGT năm 2023 được xác định như thế nào?

SOURCE CONTEXT:
 Căn cứ khoản 1, khoản 2 Điều 9 Nghị định 123/2020/NĐ-CP, thời điểm lập hóa đơn đối với bán hàng hóa và cung cấp dịch vụ được quy định rõ như sau:
Thời điểm xuất hóa đơn khi bán hàng hóa
Thời điểm lập hóa đơn đối với bán hàng hóa (bao gồm cả bán tài sản nhà nước, tài sản tịch thu, sung quỹ nhà nước và bán hàng dự trữ quốc gia) là thời điểm chuyển giao quyền sở hữu hoặc quyền sử dụng hàng hóa cho người mua, không phân biệt đã thu được tiền hay chưa thu được tiền.
Thời điểm xuất hóa đơn khi cung cấp dịch vụ
Thời điểm lập hóa đơn đối với cung cấp dịch vụ là thời điểm hoàn thành việc cung cấp dịch vụ không phân biệt đã thu được tiền hay chưa thu được tiền.
Trường hợp người cung cấp dịch vụ có thu tiền trước hoặc trong khi cung cấp dịch vụ thì thời điểm lập hóa đơn là thời điểm thu tiền (không bao gồm trường hợp thu tiền đặt cọc hoặc tạm ứng để đảm bảo thực hiện hợp đồng cung cấp các dịch vụ: Kế toán, kiểm toán, tư vấn tài chính, thuế; thẩm định giá; tư vấn giám sát; khảo sát, thiết kế kỹ thuật; lập dự án đầu tư xây dựng).
Lưu ý: Trường hợp giao hàng nhiều lần hoặc bàn giao từng hạng mục, công đoạn dịch vụ thì mỗi lần giao hàng hoặc bàn giao đều phải lập hóa đơn cho khối lượng, giá trị hàng hóa, dịch vụ được giao tương ứng.
Thời điểm lập hóa đơn trong một số trường hợp cụ thể
Theo quy định tại khoản 4 Điều 9 Nghị định 123/2020/NĐ-CP như sau:
(1) Đối với trường hợp cung cấp dịch vụ với số lượng lớn, phát sinh thường xuyên, cần có thời gian đối soát số liệu giữa doanh nghiệp cung cấp dịch vụ và khách hàng, đối tác:
Thời điểm lập hóa đơn là thời điểm hoàn thành việc đối soát dữ liệu giữa các bên nhưng chậm nhất không quá ngày 07 của tháng sau tháng phát sinh việc cung cấp dịch vụ hoặc không quá 07 ngày kể từ ngày kết thúc kỳ quy ước.
Kỳ quy ước để làm căn cứ tính lượng hàng hóa, dịch vụ cung cấp căn cứ thỏa thuận giữa đơn vị bán hàng hóa, cung cấp dịch vụ với người mua.
(2) Đối với dịch vụ viễn thông:
Thời điểm lập hóa đơn là thời điểm hoàn thành việc đối soát dữ liệu về cước dịch vụ theo hợp đồng kinh tế giữa các cơ sở kinh doanh dịch vụ nhưng chậm nhất không quá 2 tháng kể từ tháng phát sinh cước dịch vụ kết nối.
Trường hợp cung cấp dịch vụ viễn thông (bao gồm cả dịch vụ viễn thông giá trị gia tăng) thông qua bán thẻ trả trước, thu cước phí hòa mạng khi khách hàng đăng ký sử dụng dịch vụ mà khách hàng không yêu cầu xuất hóa đơn GTGT hoặc không cung cấp tên, địa chỉ, mã số thuế thì:
Cuối mỗi ngày hoặc định kỳ trong tháng, cơ sở kinh doanh dịch vụ lập chung một hóa đơn GTGT ghi nhận tổng doanh thu phát sinh theo từng dịch vụ người mua không lấy hóa đơn hoặc không cung cấp tên, địa chỉ, mã số thuế.
(3) Đối với hoạt động xây dựng, lắp đặt:
Thời điểm lập hóa đơn là thời điểm nghiệm thu, bàn giao công trình, hạng mục công trình, khối lượng xây dựng, lắp đặt hoàn thành, không phân biệt đã thu được tiền hay chưa thu được tiền.
(4) Đối với tổ chức kinh doanh bất động sản, xây dựng cơ sở hạ tầng, xây dựng nhà để bán, chuyển nhượng thì thời điểm lập hóa đơn được quy định cụ thể theo từng trường hợp khác nhau như sau:
- Chưa chuyển giao quyền sở hữu, quyền sử dụng: Có thực hiện thu tiền theo tiến độ thực hiện dự án hoặc tiến độ thu tiền ghi trong hợp đồng thì thời điểm lập hóa đơn là ngày thu tiền hoặc theo thỏa thuận thanh toán trong hợp đồng.
- Đã chuyển giao quyền sở hữu, quyền sử dụng: Thời điểm lập hóa đơn thời điểm chuyển giao quyền sở hữu hoặc quyền sử dụng hàng hóa cho người mua, không phân biệt đã thu được tiền hay chưa thu được tiền.
(5) Đối với tổ chức kinh doanh mua dịch vụ vận tải hàng không xuất qua website và hệ thống thương mại điện tử:
Thời điểm lập hóa đơn được lập theo thông lệ quốc tế chậm nhất không quá 05 ngày kế tiếp kể từ ngày chứng từ dich vụ vận tải hàng không xuất ra trên hệ thống website và hệ thống thương mại điện tử.
(6) Đối với hoạt động tìm kiếm thăm dò, khai thác và chế biến dầu thô:
- Thời điểm lập hóa đơn bán dầu thô, condensate, các sản phẩm được chế biến từ dầu thô (bao gồm cả hoạt động bao tiêu sản phẩm theo cam kết của Chính phủ) là thời điểm bên mua và bên bán xác định được giá bán chính thức, không phân biệt đã thu được tiền hay chưa thu được tiền.
- Đối với hoạt động bán khí thiên nhiên, khí đồng hành, khí than được chuyển bằng đường ống dẫn khí đến người mua:
Thời điểm lập hóa đơn là thời điểm bên mua, bên bán xác định khối lượng khí giao hàng tháng nhưng chậm nhất không quá 07 ngày kế tiếp kể từ ngày bên bán gửi thông báo lượng khí giao hàng tháng.
- Trường hợp thỏa thuận bảo lãnh và cam kết của Chính phủ có quy định khác về thời điểm lập hóa đơn thì thực hiện theo quy định tại thỏa thuận bảo lãnh và cam kết của Chính phủ.
(7) Cơ sở kinh doanh thương mại bán lẻ, kinh doanh dịch vụ ăn uống theo mô hình hệ thống cửa hàng bán trực tiếp đến người tiêu dùng nhưng việc hạch toán toàn bộ hoạt động kinh doanh được thực hiện tại trụ sở chính (trụ sở chính trực tiếp ký hợp đồng mua, bán hàng hóa, dịch vụ có in Phiếu tính tiền cho khách hàng, dữ liệu Phiếu tính tiền có lưu trên hệ thống và khách hàng không có nhu cầu nhận hóa đơn điện tử:
Cuối ngày cơ sở kinh doanh căn cứ thông tin từ Phiếu tính tiền để tổng hợp lập hóa đơn điện tử cho các giao dịch bán hàng hóa, cung cấp đồ ăn uống trong ngày.
Trường hợp khách hàng yêu cầu lập hóa đơn điện tử thì cơ sở kinh doanh lập hóa đơn điện tử giao cho khách hàng.
(8) Đối với hoạt động bán điện của các công ty phát điện trên thị trường điện thì thời điểm lập hóa đơn điện tử được xác định căn cứ thời điểm về đối soát số liệu thanh toán giữa đơn vị vận hành hệ thống điện và thị trường điện, đơn vị phát điện và đơn vị mua điện theo quy định của Bộ Công Thương hoặc hợp đồng mua bán điện đã được Bộ Công Thương hướng dẫn, phê duyệt.
Chậm nhất của thời điểm lập hóa đơn là ngày cuối cùng của thời hạn kê khai, nộp thuế đối với tháng phát sinh nghĩa vụ thuế theo quy định pháp luật về thuế.
Riêng hoạt động bán điện của các công ty phát điện có cam kết bảo lãnh của Chính phủ về thời điểm thanh toán thì thời điểm lập hóa đơn điện tử căn cứ theo bảo lãnh của Chính phủ, hướng dẫn và phê duyệt của Bộ Công Thương và các hợp đồng mua bán điện đã được ký kết giữa bên mua điện và bên bán điện.
(9) Thời điểm lập hóa đơn điện tử đối với trường hợp bán xăng dầu tại các cửa hàng bán lẻ cho khách hàng là thời điểm kết thúc việc bán xăng dầu theo từng lần bán.
Người bán phải đảm bảo lưu trữ đầy đủ hóa đơn điện tử đối với trường hợp bán xăng dầu cho khách hàng là cá nhân không kinh doanh, cá nhân kinh doanh và đảm bảo có thể tra cứu khi cơ quan có thẩm quyền yêu cầu.
(10) Đối với trường hợp cung cấp dịch vụ vận tải hàng không, dịch vụ bảo hiểm qua đại lý, thời điểm lập hóa đơn là thời điểm hoàn thành việc đối soát dữ liệu giữa các bên nhưng chậm nhất không quá ngày 10 của tháng sau tháng phát sinh.
(11) Trường hợp cung cấp dịch vụ ngân hàng, chứng khoán, bảo hiểm, dịch vụ chuyển tiền qua ví điện tử, dịch vụ ngừng và cấp điện trở lại của đơn vị phân phối điện cho người mua là cá nhân không kinh doanh (hoặc cá nhân kinh doanh) nhưng không có nhu cầu lấy hóa đơn thì cuối ngày hoặc cuối tháng đơn vị thực hiện xuất hóa đơn tổng căn cứ thông tin chi tiết từng giao dịch phát sinh trong ngày, trong tháng tại hệ thống quản lý dữ liệu của đơn vị.
Đơn vị cung cấp dịch vụ phải chịu trách nhiệm về tính chính xác nội dung thông tin giao dịch và cung cấp bảng tổng hợp chi tiết dịch vụ cung cấp khi cơ quan chức năng yêu cầu.
Nếu khách hàng yêu cầu lấy hóa đơn theo từng giao dịch thì đơn vị cung cấp dịch vụ phải lập hóa đơn giao cho khách hàng.
(12) Kinh doanh vận tải hành khách bằng xe taxi có sử dụng phần mềm tính tiền theo quy định của pháp luật thì thời điểm lập hóa đơn như sau:
- Tại thời điểm kết thúc chuyến đi, doanh nghiệp, hợp tác xã kinh doanh vận tải hành khách bằng xe taxi có sử dụng phần mềm tính tiền thực hiện gửi các thông tin của chuyến đi cho khách hàng và gửi về cơ quan thuế theo định dạng dữ liệu của cơ quan thuế.
Các thông tin gồm tên đơn vị kinh doanh vận tải, biển kiểm soát xe, cự ly chuyến đi (tính theo km) và tổng số tiền hành khách phải trả.
- Trường hợp khách hàng lấy hóa đơn điện tử thì khách hàng cập nhật hoặc gửi các thông tin đầy đủ (tên, địa chỉ, mã số thuế) vào phần mềm hoặc đơn vị cung cấp dịch vụ.
Căn cứ thông tin khách hàng gửi hoặc cập nhật, doanh nghiệp, hợp tác xã kinh doanh vận tải hành khách bằng xe taxi có sử dụng phần mềm tính tiền thực hiện gửi hóa đơn của chuyến đi cho khách hàng, đồng thời chuyển dữ liệu hóa đơn đến cơ quan thuế.
(13) Đối với cơ sở y tế kinh doanh dịch vụ khám chữa bệnh có sử dụng phần mềm quản lý khám chữa bệnh và quản lý viện phí, từng giao dịch khám, chữa bệnh và thực hiện các dịch vụ chụp, chiếu, xét nghiệm có in phiếu thu tiền (thu viện phí hoặc tiền khám, xét nghiệm) và có lưu trên hệ thống công nghệ thông tin:
- Nếu khách hàng (người đến khám, chữa bệnh) không có nhu cầu lấy hóa đơn thì cuối ngày cơ sở y tế căn cứ thông tin khám, chữa bệnh và thông tin từ phiếu thu tiền để tổng hợp lập hóa đơn điện tử cho các dịch vụ y tế thực hiện trong ngày.
- Nếu khách hàng yêu cầu lập hóa đơn điện tử thì cơ sở y tế lập hóa đơn điện tử giao cho khách hàng.
(14) Đối với hoạt động thu phí dịch vụ sử dụng đường bộ theo hình thức điện tử không dừng ngày lập hóa đơn điện tử là ngày xe lưu thông qua trạm thu phí.
Trường hợp khách hàng sử dụng dịch vụ thu phí đường bộ theo hình thức điện tử không dừng có một hoặc nhiều phương tiện cùng sử dụng dịch vụ nhiều lần trong tháng, đơn vị cung cấp dịch vụ có thể lập hóa đơn điện tử theo định kỳ, ngày lập hóa đơn điện tử chậm nhất là ngày cuối cùng của tháng phát sinh dịch vụ thu phí.
Nội dung hóa đơn liệt kê chi tiết từng lượt xe lưu thông qua các trạm thu phí, bao gồm thời gian xe qua trạm, giá phí sử dụng đường bộ của từng lượt xe.

--- strict_512 ---
Dựa trên ngữ cảnh được cung cấp, không có thông tin cụ thể về thời điểm lập hóa đơn thuế GTGT năm 2023. Tuy nhiên, theo quy định tại điểm (5) của ngữ cảnh, thời điểm lập hóa đơn GTGT được xác định như sau:

"Thời điểm lập hóa đơn được lập theo thông lệ quốc tế chậm nhất không quá 05 ngày kế tiếp kể từ ngày chứng từ dich vụ vận tải hàng không xuất ra trên hệ thống website và hệ thống thương mại điện tử."

Vì vậy, thời điểm lập hóa đơn thuế GTGT năm 2023 sẽ được xác định theo thông lệ quốc tế, chậm nhất không quá 05 ngày kế tiếp kể từ ngày chứng từ dịch vụ vận tải hàng không xuất ra trên hệ thống website và hệ thống thương mại điện tử.

--- strict_1024 ---
Dựa trên ngữ cảnh được cung cấp, không có thông tin cụ thể về thời điểm lập hóa đơn thuế GTGT năm 2023. Tuy nhiên, theo quy định tại điểm (5) của ngữ cảnh, thời điểm lập hóa đơn GTGT được xác định như sau:

"Thời điểm lập hóa đơn được lập theo thông lệ quốc tế chậm nhất không quá 05 ngày kế tiếp kể từ ngày chứng từ dich vụ vận tải hàng không xuất ra trên hệ thống website và hệ thống thương mại điện tử."

Vì vậy, thời điểm lập hóa đơn thuế GTGT năm 2023 sẽ được xác định theo thông lệ quốc tế, chậm nhất không quá 05 ngày kế tiếp kể từ ngày chứng từ dịch vụ vận tải hàng không xuất ra trên hệ thống website và hệ thống thương mại điện tử.

### ID 79987

QUESTION: Vay ưu đãi để thuê mua nhà ở xã hội theo thủ tục nào?

SOURCE CONTEXT:
 Thủ tục vay ưu đãi để thuê mua nhà ở xã hội đối với công chức Nhà nước thực hiện theo khoản 8 và khoản 9 Hướng dẫn 2526/NHCS-TDSV năm 2016 như sau:
* Hồ sơ vay vốn
- Giấy đề nghị vay vốn theo mẫu số 01/NƠXH;
- Giấy xác nhận về đối tượng và thực trạng nhà ở: Giấy xác nhận theo mẫu số 03 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT- BXD;
- Giấy chứng minh về điều kiện thu nhập:
+ Việc xác nhận về điều kiện thu nhập thực hiện đồng thời với việc xác nhận đối tượng và thực trạng nhà ở áp dụng theo mẫu số 03 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD;
+ Trường hợp công chức đã được xác nhận về đối tượng và điều kiện để được hưởng chính sách hỗ trợ nhà ở xã hội trước ngày 15/8/2016, nhưng chưa có xác nhận về điều kiện thu nhập thì phải xác nhận bổ sung về điều kiện thu nhập theo mẫu số 07 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD.
+ Trường hợp công chức đã nghỉ việc, nghỉ chế độ theo quy định của pháp luật phải tự khai và tự chịu trách nhiệm về mức thu nhập của bản thân theo mẫu số 06 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT- BXD (không cần phải có xác nhận).
- Giấy tờ chứng minh về điều kiện cư trú
+ Đối với vay vốn để mua, thuê mua nhà ở xã hội: Bản sao có chứng thực hộ khẩu thường trú hoặc giấy đăng ký hộ khẩu tập thể tại địa phương nơi có nhà ở xã hội xin mua, thuê mua. Trường hợp người vay vốn không có hộ khẩu thường trú theo quy định thì phải có:
++ Bản sao có chứng thực giấy đăng ký tạm trú có thời hạn từ một năm trở lên tính đến thời điểm nộp đơn;
++ Bản sao có chứng thực hợp đồng lao động có thời hạn từ một năm trở lên tính đến thời điểm nộp đơn hoặc hợp đồng không xác định thời hạn;
++ Giấy xác nhận (hoặc giấy tờ chứng minh) về việc có đóng bảo hiểm xã hội của cơ quan bảo hiểm tại tỉnh, thành phố trực thuộc Trung ương nơi người đó đăng ký mua, thuê mua nhà ở xã hội. Trường hợp đối tượng làm việc cho chi nhánh hoặc văn phòng đại diện tại tỉnh, thành phố nơi có nhà ở xã hội mà việc đóng bảo hiểm thực hiện tại địa phương nơi đặt trụ sở chính thì phải có giấy xác nhận của cơ quan, đơn vị nơi đặt trụ sở chính về việc đóng bảo hiểm.
+ Đối với vay vốn để xây mới hoặc cải tạo, sửa chữa nhà để ở: Bản sao có chứng thực hộ khẩu thường trú tại tỉnh, thành phố trực thuộc Trung ương nơi có đất để xây dựng mới hoặc cải tạo, sửa chữa nhà để ở.
- Ngoài giấy tờ được quy định tại điểm a, b, c, d khoản này, tùy theo từng mục đích sử dụng vốn vay phải có các giấy tờ sau:
+ Đối với vay vốn để mua, thuê mua nhà ở xã hội
++ Bản sao có chứng thực Hợp đồng mua bán nhà ở xã hội theo mẫu số 09, hoặc Hợp đồng thuê mua nhà ở xã hội theo mẫu số 11 tại Phụ lục ban hành kèm theo Thông tư 20/2016/TT-BXD;
++ Bản sao có chứng thực giấy tờ chứng minh đã đóng tiền cho chủ đầu tư để mua, thuê mua nhà ở xã hội theo Hợp đồng đã ký;
++ Biên bản bàn giao nhà ở giữa người vay vốn để thuê mua nhà ở xã hội với chủ đầu tư.
+ Đối với vay vốn để xây mới hoặc cải tạo, sửa chữa nhà để ở
++ Dự toán hoặc phương án tính toán giá thành theo mẫu số 10/NƠXH;
++ Hợp đồng thi công (nếu có);
++ Bản vẽ thiết kế và bản sao có chứng thực Giấy phép xây dựng theo quy định của pháp luật về xây dựng;
++ Bản sao có chứng thực Giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà và tài sản khác gắn liền với đất do cơ quan Nhà nước có thẩm quyền cấp theo quy định của pháp luật về đất đai tại địa phương nơi đăng ký hộ khẩu thường trú.
* Thủ tục cho vay
- Tại Tổ TK&VV
Người vay vốn gửi hồ sơ quy định tại điểm a, b, c, d khoản 8 Hướng dẫn này cho Tổ TK&VV nơi cư trú hợp pháp. Nếu người vay vốn chưa là tổ viên Tổ TK&VV thì Tổ TK&VV tại thôn, tổ dân phố (làng, ấp, bản, buôn, bon, phun, sóc... gọi chung là thôn; tổ dân phố, khu phố, khối phố, khóm, tiểu khu... gọi chung là tổ dân phố) nơi cư trú hiện nay tổ chức họp kết nạp bổ sung tổ viên; họp bình xét công khai dưới sự giám sát, chứng kiến của Trưởng thôn hoặc tổ trưởng tổ dân phố và người đại diện tổ chức chính trị - xã hội nhận ủy thác xã, phường, thị trấn (gọi chung là cấp xã); lập danh sách đề nghị vay vốn NHCSXH theo mẫu số 03a/NƠXH kèm hồ sơ vay vốn, biên bản họp Tổ gửi Ban giảm nghèo cấp xã để trình UBND cấp xã.
Đối với người vay vốn đang cư trú tại các khu nhà ở tập thể mà xa khu dân cư thì Ban giảm nghèo cấp xã tham mưu cho Chủ tịch UBND cấp xã giao cho một trong bốn tổ chức chính trị-xã hội đang nhận ủy thác là Hội Liên hiệp Phụ nữ Việt Nam, Hội Cựu chiến binh Việt Nam, Hội Nông dân Việt Nam và Đoàn Thanh niên Cộng sản Hồ Chí Minh đứng ra vận động thành lập Tổ TK&VV theo quy định.
- Tại UBND cấp xã
Căn cứ chỉ tiêu kế hoạch vốn được giao, Ban giảm nghèo cấp xã tập hợp hồ sơ của các Tổ TK&VV trong toàn xã trình Chủ tịch UBND cấp xã xác nhận trên Danh sách đề nghị vay vốn NHCSXH mẫu số 03b/NƠXH, sau đó gửi NHCSXH nơi cho vay.
Trường hợp nhu cầu vay vốn lớn hơn chỉ tiêu kế hoạch vốn được giao thì tổ chức chấm điểm theo Bảng tiêu chí chấm điểm để xét ưu tiên vay vốn nhà ở xã hội mẫu số 11/NƠXH. Căn cứ vào số điểm đã chấm để xác định số người được vay vốn theo nguyên tắc lấy điểm từ cao xuống thấp. Trường hợp tại mức chỉ tiêu kế hoạch vốn được giao mà có nhiều người bằng điểm nhau thì bốc thăm. Việc công khai điểm và bốc thăm dò Ban giảm nghèo thực hiện dưới sự chủ trì của Chủ tịch UBND cấp xã và được lập thành biên bản lưu tại xã.
- Tại NHCSXH nơi cho vay
+ Khi nhận được hồ sơ vay vốn do tổ TK&VV gửi đến, NHCSXH nơi cho vay thông báo cho người vay theo mẫu số 07/NƠXH đến làm thủ tục vay vốn và mang theo hồ sơ vay vốn quy định tại Điểm đ Khoản 8 văn bản này. Cán bộ tín dụng được Giám đốc NHCSXH nơi cho vay phân công, trong thời gian tối đa 10 ngày làm việc thực hiện thẩm định tính đầy đủ, hợp pháp, hợp lệ của hồ sơ vay vốn, lập báo cáo thẩm định theo mẫu số 02/NƠXH. Báo cáo thẩm định được lập phù hợp với từng đối tượng xin vay nhưng phải tuân thủ các nội dung theo mẫu hướng dẫn và được đánh máy.
+ Cán bộ tín dụng trình báo cáo thẩm định kèm hồ sơ vay vốn cho Trưởng phòng/Tổ trưởng tín dụng kiểm soát, sau đó trình Giám đốc NHCSXH nơi cho vay xem xét phê duyệt.
Việc kiểm soát và phê duyệt hồ sơ vay vốn kể từ khi cán bộ tín dụng được phân công thẩm định trình tối đa 05 ngày làm việc.
+ NHCSXH nơi cho vay thông báo kết quả phê duyệt cho vay theo mẫu số 04a/NƠXH hoặc không đồng ý phê duyệt cho vay theo mẫu số 04b/NƠXH.
+ Trường hợp phê duyệt cho vay thì NHCSXH nơi cho vay, người vay vốn và chủ đầu tư ký Hợp đồng ba bên theo mẫu số 14/NƠXH, lập Hợp đồng tín dụng theo mẫu số 05/NƠXH, Hợp đồng thế chấp tài sản theo mẫu số 12/NƠXH và thực hiện giao dịch bảo đảm theo quy định.
Khi ký Hợp đồng tín dụng, Hợp đồng thế chấp tài sản, người vay vốn phải xuất trình bản gốc: Giấy tờ chứng minh đã đóng tiền cho chủ đầu tư để mua, thuê mua nhà ở xã hội theo Hợp đồng đã ký; Hợp đồng mua bán nhà ở xã hội/Hợp đồng thuê mua nhà ở xã hội hoặc giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà ở và tài sản khác gắn liền với đất; Giấy tờ khác liên quan đến tài sản bảo đảm để đối chiếu.
Các Hợp đồng nêu trên được lập phù hợp với từng đối tượng vay vốn, loại tài sản bảo đảm,... nhưng phải tuân thủ các nội dung theo mẫu hướng dẫn và được đánh máy.
+ Căn cứ Hợp đồng tín dụng đã được ký kết giữa người vay vốn với NHCSXH nơi cho vay, người vay vốn mở tài khoản tiền gửi để gửi tiền tiết kiệm hàng tháng theo quy định và thực hiện gửi ngay từ tháng ký hợp đồng tín dụng.
+ Sau khi hồ sơ vay vốn được hoàn thiện, cán bộ thẩm định chuyển cho bộ phận kế toán làm căn cứ giải ngân. Các giấy tờ bàn giao cho bộ phận kế toán bao gồm:
++ Giấy đề nghị vay vốn;
++ Báo cáo thẩm định;
++ Hợp đồng tín dụng;
++ Hợp đồng thế chấp tài sản đã công chứng;
++ Biên bản kiểm tra về tiến độ công trình - đối với người vay vốn để xây dựng mới hoặc cải tạo, sửa chữa nhà để ở: chứng minh người vay vốn đã dùng vốn tự có theo quy định để xây dựng mới hoặc cải tạo, sửa chữa nhà để ở theo mẫu số 06/NƠXH;
++ Giấy đề nghị giải ngân theo mẫu số 15/NƠXH.
+ Kế toán chỉ được phát tiền vay sau khi người vay vốn đã thực hiện gửi tiền tiết kiệm theo quy định và đã làm thủ tục nhập kho bản gốc: Hợp đồng thế chấp tài sản đã có công chứng; Giấy tờ liên quan đến bảo đảm tiền vay; Hợp đồng mua bán nhà ở xã hội/Hợp đồng thuê mua nhà ở xã hội của người vay vốn với chủ đầu tư hoặc giấy chứng nhận quyền sử dụng đất, quyền sở hữu nhà ở và tài sản khác gắn liền với đất; Biên bản bàn giao nhà ở giữa người vay vốn để thuê mua nhà ở xã hội với chủ đầu tư; Giấy tờ chứng minh đã đóng tiền cho chủ đầu tư.
+ Các giấy tờ còn lại được lưu tại bộ phận tín dụng.
Mức vay ưu đãi để thuê mua nhà ở xã hội là bao nhiêu?
Công chức được vay ưu đãi để thuê nhà ở xã hội với mức vay được quy định tại điểm a khoản 4 Hướng dẫn 2526/NHCS-TDSV năm 2016 như sau:
Trường hợp mua, thuê mua nhà ở xã hội: Mức vốn cho vay tối đa bằng 80% giá trị hợp đồng mua, thuê mua nhà ở xã hội.
Như vậy, ta thấy công chức Nhà nước nếu đáp ứng đầy đủ các diều kiện theo quy định thì được phép vay ưu đãi để thuê mua nhà ở xã hội. Để thực hiện hoạt động này, công chức chuẩn bị hồ sơ và tiến hành đăng ký vay vốn theo trình tự quy định. Mức vay vốn áp dụng đối với vay ưu đãi để thuê mua nhà ở xã hội bằng tối đa bằng 80% giá trị hợp đồng mua, thuê mua nhà ở xã hội.

--- strict_512 ---
Dựa trên ngữ cảnh được cung cấp, thủ tục vay ưu đãi để thuê mua nhà ở xã hội theo các bước sau:

1. **Chuẩn bị hồ sơ vay vốn:**
   - **Giấy đề nghị vay vốn:** Theo mẫu số 01/NƠXH.
   - **Giấy xác nhận về đối tượng và thực trạng nhà ở:** Theo mẫu số 03 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD.
   - **Giấy chứng minh về điều kiện thu nhập:**
     - Trường hợp công chức đã được xác nhận về đối tượng và điều kiện để được hưởng chính sách hỗ trợ nhà ở xã hội trước ngày 15/8/2016, nhưng chưa có xác nhận về điều kiện thu nhập thì phải xác nhận bổ sung về điều kiện thu nhập theo mẫu số 07 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD.
     - Trường hợp công chức đã nghỉ việc, nghỉ chế độ theo quy định của pháp luật phải tự khai và tự chịu trách nhiệm về mức thu nhập của bản thân theo mẫu số 06 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD (không cần phải có xác nhận).
   - **Giấy tờ chứng minh về điều kiện cư trú:**
     - Đối với vay vốn để mua, thuê mua nhà ở xã hội: Bản sao có chứng thực hộ khẩu thường trú hoặc giấy đăng ký hộ khẩu tập thể tại địa phương nơi có nhà ở xã hội xin mua, thuê mua. Trường hợp người vay vốn không có hộ khẩu thường trú theo quy định thì phải có:
       - Bản sao có chứng thực giấy đăng ký tạm trú có thời hạn từ một năm trở lên tính đến thời điểm nộp đơn.
       - Bản sao có chứng thực hợp đồng lao động có thời hạn từ một năm trở lên tính đến thời điểm nộp đơn hoặc hợp đồng không xác định thời hạn.
       - Giấy xác nhận (hoặc giấy tờ chứng minh) về việc có đóng bảo hiểm xã hội của cơ quan bảo hiểm tại tỉnh, thành phố trực thuộc Trung ương nơi người đó đăng ký mua, thuê mua nhà ở xã hội. Trường hợp đối tượng

--- strict_1024 ---
Dựa trên ngữ cảnh được cung cấp, thủ tục vay ưu đãi để thuê mua nhà ở xã hội theo các bước sau:

1. **Chuẩn bị hồ sơ vay vốn:**
   - **Giấy đề nghị vay vốn:** Theo mẫu số 01/NƠXH.
   - **Giấy xác nhận về đối tượng và thực trạng nhà ở:** Theo mẫu số 03 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD.
   - **Giấy chứng minh về điều kiện thu nhập:**
     - Trường hợp công chức đã được xác nhận về đối tượng và điều kiện để được hưởng chính sách hỗ trợ nhà ở xã hội trước ngày 15/8/2016, nhưng chưa có xác nhận về điều kiện thu nhập thì phải xác nhận bổ sung về điều kiện thu nhập theo mẫu số 07 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD.
     - Trường hợp công chức đã nghỉ việc, nghỉ chế độ theo quy định của pháp luật phải tự khai và tự chịu trách nhiệm về mức thu nhập của bản thân theo mẫu số 06 tại Phụ lục I ban hành kèm theo Thông tư 20/2016/TT-BXD (không cần phải có xác nhận).
   - **Giấy tờ chứng minh về điều kiện cư trú:**
     - Đối với vay vốn để mua, thuê mua nhà ở xã hội: Bản sao có chứng thực hộ khẩu thường trú hoặc giấy đăng ký hộ khẩu tập thể tại địa phương nơi có nhà ở xã hội xin mua, thuê mua. Trường hợp người vay vốn không có hộ khẩu thường trú theo quy định thì phải có:
       - Bản sao có chứng thực giấy đăng ký tạm trú có thời hạn từ một năm trở lên tính đến thời điểm nộp đơn.
       - Bản sao có chứng thực hợp đồng lao động có thời hạn từ một năm trở lên tính đến thời điểm nộp đơn hoặc hợp đồng không xác định thời hạn.
       - Giấy xác nhận (hoặc giấy tờ chứng minh) về việc có đóng bảo hiểm xã hội của cơ quan bảo hiểm tại tỉnh, thành phố trực thuộc Trung ương nơi người đó đăng ký mua, thuê mua nhà ở xã hội. Trường hợp đối tượng làm việc cho chi nhánh hoặc văn phòng đại diện tại tỉnh, thành phố nơi có nhà ở xã hội mà việc đóng bảo hiểm thực hiện tại địa phương nơi đặt trụ sở chính thì phải có giấy xác nhận của cơ quan, đơn vị nơi đặt trụ sở chính về việc đóng bảo hiểm.
     - Đối với vay vốn để xây mới hoặc cải tạo, sửa chữa nhà để ở: Bản sao có chứng thực hộ khẩu thường trú tại tỉnh, thành phố trực thuộc Trung ương nơi có đất để xây dựng mới hoặc cải tạo, sửa chữa nhà để ở.

2. **Gửi hồ sơ:**
   - Người vay vốn gửi hồ sơ quy định tại điểm a, b, c, d khoản 8 Hướng dẫn này cho Tổ TK&VV nơi cư trú hợp pháp. Nếu người vay vốn chưa là tổ viên Tổ TK&VV thì Tổ TK&VV tại thôn, tổ dân phố (làng, ấp, bản, buôn, bon, phun, sóc... gọi chung là thôn; tổ dân phố, khu phố, khối phố, khóm, tiểu khu... gọi chung là tổ dân phố) nơi cư trú hiện nay tổ chức họp kết nạp bổ sung tổ viên; họp bình xét công khai dưới sự giám sát, chứng kiến của Trưởng thôn hoặc tổ trưởng tổ dân phố và người đại diện tổ chức chính trị - xã hội nhận ủy thác xã, phường, thị trấn (gọi chung là cấp xã); lập danh sách đề nghị vay vốn NHCSXH theo mẫu số 03a/NƠXH kèm hồ sơ vay vốn, biên bản họp Tổ gửi Ban giảm nghèo cấp xã để trình UBND cấp xã.

3. **Xét duyệt hồ sơ:**
   - Tại UBND cấp xã:
     - Căn cứ chỉ tiêu kế hoạch vốn được giao, Ban giảm nghèo cấp xã tập hợp hồ sơ của các Tổ TK&VV trong toàn xã trình Chủ tịch UBND cấp xã xác nhận trên Danh sách đề nghị vay vốn NHCSXH mẫu số 03b/NƠXH, sau đó gửi NHCSXH nơi cho vay.
     - Trường hợp nhu cầu vay vốn lớn hơn chỉ tiêu kế hoạch vốn được giao thì tổ chức chấm điểm theo Bảng tiêu chí chấm điểm để xét ưu tiên vay vốn nhà ở xã hội mẫu số 11/NƠXH. Căn cứ vào số